### ISSUE TITLE
Add hero.phrases(s)

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#10]
(Edited)

For some NLP tasks, it's useful to merge tokens together. For instance "New York" should be considered as a single word: "New_York".

As of now, `tokenize_with_phrases` from [preprocessing.py](https://github.com/jbesomi/texthero/blob/master/texthero/preprocessing.py) does exactly that. This function is not published now on the website.

`tokenize_with_phrases` uses Gensim [PhrasesTransformer](https://radimrehurek.com/gensim/sklearn_api/phrases.html) on a tokenized text. In turn, _PhrasesTransformer_ implement the "phrases algorithm" from [Mikolov, et. al Word2Vec authors Distributed Representations of Words and Phrases and their Compositionality](https://arxiv.org/abs/1310.4546)

The actual solution of using `tokenize_with_phrases` is not optimal as this function call `hero.tokenize`. A better alternative would be to add a separate function, i.e hero.phrases(s) that given an __already tokenized__ function it creates phrases, by merging token together.

hero.phrases(s, ...)

**Where**:
 - s is a Tokenized Pandas Series
 - for the other arguments look at `tokenize_with_phrases`

**Returns**:
A Tokenized Pandas Series with phrases.

**TODO**:
- The function might be instead called `add_phrases` or `merge_with_phrases`.
- Can add an argument `symbol` for the merging symbol. Example symbol="__" --> New__York

**How to**
Rename `tokenize_with_phrases` and adapt it. Not much need to be done actually :)

**Comment by selimelawwa** [comment]
@jbesomi please explain more details, how do you need to support this. In which functions..etc

**Comment by jbesomi** [comment]
Look at [nlp.py](https://github.com/jbesomi/texthero/blob/master/texthero/nlp.py). `noun_chunks` return relevant noun phrases that it's similar.

Wondering if we want a function that just returns the top-ngrams, for instance when n=2, all couple of words "hello world" most common in a given text. 

We need to understand if such functionality might be useful for someone.
