### ISSUE TITLE
CI Pipeline: Vercel Deployment 404 Error

### ISSUE THREAD

**Issue by henrifroese** [jbesomi/texthero#110]
In PRs, in the CI Pipeline, the Vercel Deployment is marked green :heavy_check_mark: , but when clicking on "Details", we get a 404 error on the website.

![Screenshot from 2020-07-20 22-19-46](https://user-images.githubusercontent.com/50276689/87982645-6769fc80-cad7-11ea-8a4c-c36692187519.png)

**Comment by jbesomi** [comment]
Can you please post the hyperlinks of the PR and the "Details"? Sorry but I'm not understanding

**Comment by henrifroese** [comment]
Just updated the issue with an image above, thought it might be confusing :nail_care: 

This is the link it points to: https://vercel.com/jbesomi/texthero/3095yv9ig

**Comment by jbesomi** [comment]
I'm closing this as this should be over.
