### ISSUE TITLE
Extract entities from text

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#13]
Need an efficient way to extract entities from text.

**Comment by selimelawwa** [comment]
Should we use spaCy NER? or do you have another idea in mind? @jbesomi

**Comment by jbesomi** [comment]
Implemented, see here: [nlp.py](https://github.com/jbesomi/texthero/blob/master/texthero/nlp.py). What is left done is do adding documentation.

**Comment by selimelawwa** [comment]
@jbesomi Close the issue then.
