### ISSUE TITLE
How to set up development environment?

### ISSUE THREAD

**Issue by ParthGandhi** [jbesomi/texthero#15]
Also how do you run tests and build documentation locally?

**Comment by jbesomi** [comment]
Hi ParthGandhi,

thank you for opening an issue!

There is not really a development environment now. For now and to keep things simple, the idea is to simply fork the repo, make the changes and add a pull request.

To execute the tests, you can run `./check.sh`. This also check the doctests in the docstring.

The documentation is built with [docusaurus](https://docusaurus.io/). If, for any reason, you wants to see it locally, you need to:

- cd website
- `npm run start` (you need to install node and some other dependencies)

Also, there is a tricky part. The [API](https://texthero.org/docs/api-preprocessing) docs are created from Sphinx. If you make some changes to the code and wants to see the changes in the doc, you need to go under /website/docs and call `./create_docs_with_sphinx.sh`.

Also, have a look at `push_pip.sh`. Before sending the update version to pypi, it checks that all tests pass and it also update the documentation (by calling `./create_docs_with_sphinx.sh` )

Any idea on how to deal with production/development/push/git and git hooks is more than welcome. I'm not an expert in that field.

Regards
