### ISSUE TITLE
Doctests fail with new Black version.

### ISSUE THREAD

**Issue by henrifroese** [jbesomi/texthero#171]
As we could see in #169 and #170 , with the [new release of black](https://github.com/psf/black/releases) three days ago, many of our doctests fail. We opened an issue [here at Black's Github](https://github.com/psf/black/issues/1654). Currently, when we want to push something new to Texthero, Travis CI will fail. Current hotfix is to use the last version before the release by setting in `.travis.yml`: `- pip3 install black==19.10b0` and in `setup.cfg`: `black==19.10b0`.

**Comment by jbesomi** [comment]
@henrifroese thanks! Can I close this issue?

**Comment by henrifroese** [comment]
yes should be good
