### ISSUE TITLE
Issues with _types

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#180]
- Fix type checks to not fail if first value in series is NaN/missing, see #174
- We don't need anymore to check for RepresentationSeries
- Then we might not need to check for the number of levels .. `or s.index.nlevels != 1`? Or if we do we should have a separate warning message "number of level is too high ..."
- At line [163](https://github.com/jbesomi/texthero/blob/master/texthero/_types.py#L163) of `_types` is written: "Check if a given Pandas Series has the properties of a RepresentationSeries.". Shouldn't we check for VectorSeries instead?
- Some new representation functions might accept as input both a `DataFrame` and a `VectorSeries`. Does `InputSeries` deal with that? Do we need a more general approach?

**Comment by henrifroese** [comment]
#### Checklist for the items:

- [ ] Fix type checks to not fail if first value in series is NaN/missing, see #174
- [ ] We don't need anymore to check for RepresentationSeries
- [ ] Then we might not need to check for the number of levels .. `or s.index.nlevels != 1`? Or if we do we should have a separate warning message "number of level is too high ..."
- [ ] At line [163](https://github.com/jbesomi/texthero/blob/master/texthero/_types.py#L163) of `_types` is written: "Check if a given Pandas Series has the properties of a RepresentationSeries.". Shouldn't we check for VectorSeries instead?
- [ ] Some new representation functions might accept as input both a `DataFrame` and a `VectorSeries`. Does `InputSeries` deal with that? Do we need a more general approach?

**Comment by henrifroese** [comment]
Will leave this open until #157 is merged as we might encounter some more issues etc. :shrug: :man_shrugging: :woman_shrugging:

**Comment by henrifroese** [comment]
Can be closed as #157 is merged, see comment above.
