### ISSUE TITLE
fillna should support customized fill content

### ISSUE THREAD

**Issue by monkdou0** [jbesomi/texthero#182]
texthero.preprocessing.fillna()  only replace the nan with writespace.
It should support customized fill content

**Comment by henrifroese** [comment]
Makes sense. This looks like a good first issue! Do you want to work on this? @monkdou0

**Comment by monkdou0** [comment]
Of course.
I will try and then give the PR

**Comment by k0pernicus** [comment]
I think this issue has been solved in #190, no?

**Comment by jbesomi** [comment]
Right, thank you @k0pernicus!
