### ISSUE TITLE
remove_diacritics for other languages

### ISSUE THREAD

**Issue by M-I-Dx** [jbesomi/texthero#201]
I am working on a dataset that has text from English, Japanese, Italian, Dutch, Spanish, German and Swedish. I want to know that happens if I run the remove_diacritics on this dataset. Also how does it effect the emojis present in the text.

**Comment by henrifroese** [comment]
Hi, `remove_diacritics` internally transfors a given text to its [NFKD normal form](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms) and then throws out all characters that are [combining](https://en.wikipedia.org/wiki/Combining_character). So it won't affect any emojis :ok_hand:

**Comment by M-I-Dx** [comment]
What about characters specific to other languages?

**Comment by mk2510** [comment]
which characters do you have in mind? But like @henrifroese mentioned the [NFKD normal form](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms) includes all normal characters from these languages. For Japanese, it would be helpful if you could specify, which writing system you want to process 🥇 

However, if you just try out the special characters with the function, you can test by yourself, how it behaves 😉

**Comment by jbesomi** [comment]
Thanks @mk2510 and @henrifroese for your help! @M-I-Dx do you have any updates? Otherwise, I will close the issue.
