### ISSUE TITLE
I can help with the spanish.

### ISSUE THREAD

**Issue by kennylajara** [jbesomi/texthero#205]
I recently found this library and I really like it.

I am certainly not an expert in machine learning but I hope to help and learn a lot while contributing to the development of the library.

**Comment by kennylajara** [comment]
Almost 2 weeks and no answer received. I am closing this issue.

**Comment by jbesomi** [comment]
Hey @kennylajara, sorry for the late reply. Right now, we are more focused on bringing a new version (2.0) with the HeroSeries, rather than the multilingual approach. I will adapt the README to mirror this change. If you are interested in helping out, I suggest you read here: #200.
Thanks,
