### ISSUE TITLE
Help Needed for TODO 

### ISSUE THREAD

**Issue by harishsdev** [jbesomi/texthero#208]
Hi Team,
 
 I saw TODO  in representation.py,can some one tell me what exactly is required here,
 
 please guide what is add here such that i can also contribute
 
 Regards,
 S.Harish

**Comment by jbesomi** [comment]
Hey @harishsdev,  in `representation.py` there are some missing documentation links. Almost all TODO refers to that, at the exception of one TODO that refers to the introduction of Topic modeling (#163). If you want to help, we are planning the release of Version 2.0, have a look and comment directly there please: #200
