### ISSUE TITLE
[Bugs] : 'gensim.sklearn_api' and Unicode issue

### ISSUE THREAD

**Issue by VinayChaudhari1996** [jbesomi/texthero#209]
Hello Guys,

`Version : texthero 1.0.9`
`python : 3.7.10
`

 **BUG 1**
____
![image](https://user-images.githubusercontent.com/42869040/120081620-2e79bb80-c0dc-11eb-947e-ee589d9cd698.png)

 **BUG 2**
____

For fixing this issue, I installed **texthero==1.0.5** but I get a second issue,

![image](https://user-images.githubusercontent.com/42869040/120081739-b8298900-c0dc-11eb-8813-c1482dedac56.png)

Thanks,

**Comment by henrifroese** [comment]
This was solved in #206 but it's not yet published so `pip install` doesn't get that yet.

Try doing  `pip install git+https://github.com/jbesomi/texthero.git`

**Comment by VinayChaudhari1996** [comment]
Hi @henrifroese 

Thanks for response ,
But how can I add it in requirements.txt ?
I'm deploying automatic build.

**Comment by henrifroese** [comment]
Instead of `texthero`, put the line `git+git://github.com/jbesomi/texthero.git#egg=texthero` into the requirements.txt, that should work

**Comment by VinayChaudhari1996** [comment]
Thanks @henrifroese 
It works for me :)
