### ISSUE TITLE
import texthero error

### ISSUE THREAD

**Issue by karndeepsingh** [jbesomi/texthero#210]
When I am trying to import texthero it throws and error saying :
ModuleNotFoundError: No module named 'gensim.sklearn_api'

I tried installing gensim and upgraded it but nothing seems to work. Any help would be appreciated.

**Comment by henrifroese** [comment]
Check here https://github.com/jbesomi/texthero/issues/209 if that helps, i.e. do ` pip install git+https://github.com/jbesomi/texthero.git` (if you already have texthero, maybe do `pip uninstall texthero` first)

**Comment by henrifroese** [comment]
@jbesomi maybe you can put this onto the README until the next version is on PyPI, so people know how they can install texthero as `pip install texthero` is not working currently

**Comment by jbesomi** [comment]
Thanks for pointing this out @karndeepsingh and @henrifroese for your quick reply.

I believe we should fix that directly on pip. I will make a release tonight that includes #209.

Thanks!

**Comment by jbesomi** [comment]
Hey! I just released Texthero 1.1.0 that should hopefully fix that issue. Would you mind downloading and try and let me know in case of any issue? Thanks!

**Comment by Akash-Rawat** [comment]
> pip install git+https://github.com/jbesomi/texthero.git

tysm, it worked in my case. I had error that was saying, import module error

**Comment by avinashpaul** [comment]
> pip install git+https://github.com/jbesomi/texthero.git

thanks this worked
