### ISSUE TITLE
Module has no name errors

### ISSUE THREAD

**Issue by cameronstewart** [jbesomi/texthero#211]
![image](https://user-images.githubusercontent.com/418413/122333902-6ea9bc80-cf6b-11eb-8779-710f06727816.png)
Please help

**Comment by henrifroese** [comment]
Try `pip uninstall texthero`, then `pip install git+https://github.com/jbesomi/texthero.git`

**Comment by cameronstewart** [comment]
Hi @henrifroese , done this, it seems that any of the nlp functions are not working.  have installed spacy separately.

Even simple things like this are not working, produce same errors.
![image](https://user-images.githubusercontent.com/418413/124062228-f0691200-da62-11eb-99ad-4a6cc644eaa4.png)

All other things work great (eg tfidf, scatter plots etc as per your documentation)

**Comment by jbesomi** [comment]
Hi @cameronstewart, for some reason, your version of texthero in the jupyter notebook is < 1.0.8. Note that most of texthero.nlp functions have been introduced on Texthero 1.0.8 onwards.

If you are using conda, make sure you have installed Texthero in your current environment.

I'm closing this issue, feel free to open it again in case of need.
Best,
