### ISSUE TITLE
How to retrieve TDIDF feature names 

### ISSUE THREAD

**Issue by plaban1981** [jbesomi/texthero#213]
Like in sklearn 
from sklearn.feature_extraction.text import TfidfVectorizer
vect =TfidfVectorizer(max_features=100)
vect_text=vect.fit_transform(rev['clean_text'])

we can retrieve feature names corresponding to the vectors using vect.get_feature_names()

is there a similar functionality in texthero ?

**Comment by jbesomi** [comment]
Hi @plaban1981, as explained in the [TFIDF API page](https://texthero.org/docs/api/texthero.representation.tfidf) you should be able to obtain features names by setting "return_features_names=True" on the tfidf function. Hope it helps! I'm closing this issue.
