### ISSUE TITLE
Visualization of PCA on embedding space with multi-labels

### ISSUE THREAD

**Issue by cassin-edwin** [jbesomi/texthero#232]
I see that this library can plot the pca of the texts on embedding space and categorize them if they are annotated with classes (Multi-class classification). But can we visualize similarly for multi-label classification?

**Comment by jbesomi** [comment]
Thanks for reaching out. 

Not directly. One possible approach you could try is to sort and count all labels, and then select the most frequent label for each document.

Hope that helps,
Jonathan
