### ISSUE TITLE
cannot import NLTKWordTokenizer

### ISSUE THREAD

**Issue by weiexcelpro** [jbesomi/texthero#32]
Should I install a specific version of NLTK?

when I run :
`import texthero as hero
import pandas as pd

df = pd.read_csv(
   "dataset/bbcsport.csv"
)

df['pca'] = (
   df['text']
   .pipe(hero.clean)
   .pipe(hero.tfidf)
   .pipe(hero.pca)
)
hero.scatterplot(df, 'pca', color='topic', title="PCA BBC Sport news")`

I got this output: 

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/aistudio/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
⚠ Skipping model package dependencies and setting `--no-deps`. You
don't seem to have the spaCy package itself installed (maybe because you've
built from source?), so installing the model dependencies would cause spaCy to
be downloaded, which probably isn't what you want. If the model package has
other dependencies, you'll have to install them manually.
✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
---------------------------------------------------------------------------ImportError                               Traceback (most recent call last)<ipython-input-7-36c2db7adf23> in <module>
----> 1 import texthero as hero
      2 import pandas as pd
      3 
      4 df = pd.read_csv(
      5    "dataset/bbcsport.csv"
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/texthero/__init__.py in <module>
     10 from .representation import *
     11 
---> 12 from . import visualization
     13 from .visualization import *
     14 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/texthero/visualization.py in <module>
      7 
      8 from wordcloud import WordCloud
----> 9 from nltk import NLTKWordTokenizer
     10 
     11 from texthero import preprocessing
ImportError: cannot import name 'NLTKWordTokenizer' from 'nltk' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/nltk/__init__.py)

**Comment by jbesomi** [comment]
Hey Wei, thank you for opening an issue!

By updating NLTK you should automatically solve the problem:

```
pip install -U nltk
```

I will fix this in the upcoming version. Please let us know if that worked.

Regards,

**Comment by pengyong94** [comment]
Sorry,it does not work.i had updated to NLTK-3.5
expect  for upcoming version

**Comment by jbesomi** [comment]
Ok. Will fix this shortly, already in a couple of hours, I guess.

Another question. If you fire up python3 and run

```
from nltk import NLTKWordTokenizer
```

Does it work?

I tried on my PC with NLTK 3.5 and it worked fine.

**Comment by jbesomi** [comment]
Version 1.0.9 has been released. This should have solved the issue. May you please check and let me know?
Thank you in advance!

**Comment by weiexcelpro** [comment]
> Version 1.0.9 has been released. This should have solved the issue. May you please check and let me know?
> Thank you in advance!

Many thanks, I will try it right now~~

**Comment by weiexcelpro** [comment]
> Sorry,it does not work.i had updated to NLTK-3.5
> expect for upcoming version

it worked! Thank you all!
