### ISSUE TITLE
Kmeans topics detection

### ISSUE THREAD

**Issue by ymentha14** [jbesomi/texthero#5]
A feature involving topics detection for unsupervised learning  (KMeans for ex) would be really welcome!

**Comment by jbesomi** [comment]
Thank you @ymentha14.

Version 1.0.4 supports `representation.do_kmeans`, `representation.do_dbscan` and `representation.do_meanshift`

Example:

```python
import texthero as hero
import pandas as pd

df = pd.read_csv(
    "https://github.com/jbesomi/texthero/raw/master/dataset/bbcsport.csv"
)

df['tfidf'] = (
    df['text']
    .pipe(hero.clean)
    .pipe(hero.do_tfidf)
)

df['pca'] = df['tfidf'].pipe(hero.do_pca)
df['kmeans_labels'] = df['tfidf'].pipe(hero.do_kmeans, n_clusters=5)

hero.scatterplot(df, 
                 col='pca', 
                 color='kmeans_labels', 
                 title="PCA BBC Sport news")
```

Return the following scatterplot:

![scatterplot](https://raw.githubusercontent.com/jbesomi/texthero/master/website/static/figure/scatterplot_bccsport_kmeans.svg)
