### ISSUE TITLE
Scatterplot color with Boolean values is not rendering properly

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#6]
On `texthero.visualization.scatterplot`, when a column of boolean values is passed as `color` arguments, no colors are rendered.

**Comment by cedricconol** [comment]
@jbesomi can you show the steps to recreate this bug? `texthero.visualization.scatterplot` with boolean values as color seem to be working fine for me.

**Comment by jbesomi** [comment]
Hey @cedricconol, thank you for pointing this out! Until recently, we were using `plotly_express` instead of `plotly.express`. `plotly_express` wasn't updated since more than one year and had this kind of bugs. So, just by moving to `plotly.express` we solved this issue. I will close it now then; thank you again!

P.s if you are interested in helping out with the `visualization.py` module, these two related issues need some help: #77 and #78! :)

**Comment by cedricconol** [comment]
Yes, I'm interested in helping! I'll take a look at those issues. Thanks @jbesomi!
