### ISSUE TITLE
count(s) and term_frequency(s)

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#61]
Texthero's  `hero.term_frequency(s)` should be reanamed `hero.count(s)` as in reality it just count the term.
Because of that, we should add another function that implements `hero.term_frequency` that is: "(number of times term t appears in a document) / (Total number of terms in the document).

The distinctions between the two should be made clear in both docstring and both functions should have a "See Also" to let the user quickly move from one function documentation to the other.

Both implementations might be written using scikit-learn CountVectorizer.

**Comment by avinashbhat** [comment]
If I understand correctly, the existing ```term_frequency``` method has to be renamed to ```count``` without any modification except that in the docstring, and another ```term_frequency``` method needs to be defined?
