### ISSUE TITLE
Spanish translation contribution

### ISSUE THREAD

**Issue by JoseDeFreitas** [jbesomi/texthero#63]
Hello 👋. My name is José De Freitas, I'm a native Spanish speaker and I can help contribute to this project by translating it into Spanish. I'm opening this issue because I saw in the README file that you'll like multilingual support and content.

## About me

I born in a Spanish language-country. Spanish is my main language. I started learning English at the age of 4 (and I'm still doing it).
I've recently made a translation from English to Spanish of the [clean-code-typescript](https://github.com/labs42io/clean-code-typescript) repository. I've also translated some small texts for friends.

## Where can I contribute

I can help translate the documentation and the tutorials about how to use texthero as well as add multilanguage support in Spanish.
I have no experience with Python nor text-data and things related, but if it's only to translate English text into Spanish, I can do it.
My time of investment in this project is moderated but not that fixed, I can work some hours per week (depending on how many texts I have to translate).

## More translators

It seems that this project will increase a lot, that's why if any other Spanish speaker who wants to help me contribute to this project in the Spanish translation can do it, and it'll be great get your help.

**Comment by jbesomi** [comment]
Hi @JoseDeFreitas! Thanks a lot for the great introduction and your willingness to help, we are glad to have you there!

Translating all the documentation from English to Spanish might be a valuable feature for all the Hispanosphere! Great initiative!

Before permitting that, we will need to put in place a system to allow that. We will need at least a week to put this system on. We will be back to you as soon as possible!

Regards,

**Comment by JoseDeFreitas** [comment]
Hello. I'm no longer interested in translating the content of this repository into Spanish. Sorry, and thank you for the opportunity anyway.
