### ISSUE TITLE
Allow a custom stop-words list

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#7]
Allow a custom stop-words list to `remove_stop_words` function

**Edit** Starting from v1.0.6, the function is called `remove_stopwords` (without the second underscore)

**Comment by Bronzekorean** [comment]
Hi Jonathan,

The project is very good and can save a lot of time for data exploration.

I've started working on this issue. I think the default behavior should still be to have the nltk stopwords.

I though of three ways to solve this: 
1- remove_stop_words(input: pd.Series, stop_words=stopwords.words("english"))
     raises two problems:
        - default is mutable
        - can't import without downloading the nltk stopwords before

2-  remove_stop_words(input: pd.Series, stop_words=None ) is less intuitive and requires adding a condition in the function core

3-  remove_stop_words(input: pd.Series, stop_words="english") have the stop_words be either a language to load from nltk or an iterable of strings


Which one do you think is best?

**Comment by jbesomi** [comment]
Hi Bronzekorean, 

thank you for your positive replay and thank you for your help!

I agree with you we need to figure out a nice solution.

What do you think if we do like that:

Add a `get_default_stop_words()`
  - returns the defaukt NLTK stopwords
  - (addition) extra argument (`spacy=False`?) to decide whereas to return NLTK default words or SpaCy default words

Edit `remove_stop_words(input, stop_words=get_default_stop_words())`
- default stopwords is `get_default_stop_words()`
- In case a user wants a custom, it replaces the default with his own.
- It can also load `get_default_stop_words()` and append his own custom stop words.

**Comment by ParthGandhi** [comment]
another way is to use a file with a namespaced attribute instead of a method i.e.

```python
from texthero import stop_words

remove_stopwords(input, stop_words.default)
remove_stopwords(input, stop_words.nltk)
remove_stopwords(input, stop_words.spacy_en)
remove_stopwords(input, None)
```

**Comment by jbesomi** [comment]
It's also a good idea. Pick one and it's gonna be fine; as long as it's consistent.
