### ISSUE TITLE
WordCloud: TypeError: wordcloud() got an unexpected keyword argument 'min_font_size' and 'max_font_size'

### ISSUE THREAD

**Issue by vidyap-xgboost** [jbesomi/texthero#77]
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-58-9c76fea65749> in <module>()
----> 1 hero.visualization.wordcloud(df1['clean_tweet'],width = 200, height= 200,background_color='White',min_font_size=2)

TypeError: wordcloud() got an unexpected keyword argument 'min_font_size'
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-951ae06e0982> in <module>()
----> 1 hero.visualization.wordcloud(df1['clean_tweet'],width = 200, height= 200,background_color='White',max_font_size=8)

TypeError: wordcloud() got an unexpected keyword argument 'max_font_size'
```

I am working on Google Colab and tried using the argument `min_font_size` to change it from `default` value `4` to `2`. But it gives me a TypeError.

Although the [documentation](https://texthero.org/docs/api/texthero.visualization.wordcloud) says the method has the argument, it doesn't take in this argument when changed to another value.

Was this feature removed or yet to be added?

**Comment by jbesomi** [comment]
Good catch!

There are two things that going on there:

1. You should update Texthero `pip install texthero -U`
2. The code will "work", but the size will not change. The reason is that looking at the [source code](https://github.com/jbesomi/texthero/blob/master/texthero/visualization.py) we are not passing `min_font_size` parameter to the underline word cloud object.  Also, `min_font_size` is missing too. The bottom line is that we should make more test for this and check all parameters, one after the other!

Do you want to help fix that?

**Comment by vidyap-xgboost** [comment]
> Good catch!
> 
> There are two things that going on there:
> 
> 1. You should update Texthero `pip install texthero -U`
> 2. The code will "work", but the size will not change. The reason is that looking at the [source code](https://github.com/jbesomi/texthero/blob/master/texthero/visualization.py) we are not passing `min_font_size` parameter to the underline word cloud object.  Also, `min_font_size` is missing too. The bottom line is that we should make more test for this and check all parameters, one after the other!
> 
> Do you want to help fix that?

I would love to!

Just checked for `max_font_size` and its the same error. As you rightly pointed out, the source code's word cloud object doesn't have these parameters.

However, any directions for a beginner to contribute in correcting the source code?

**Comment by jbesomi** [comment]
Sure!

This document: [CONTRIBUTING.md](https://github.com/jbesomi/texthero/blob/master/CONTRIBUTING.md) guide you through all the details.

The big picture is:

1. Fork and download locally the repo
1. Install texthero locally
1. Made the changes (in this case under `visualization.py`)
1. Add new test (under `test_visualization.py` you can start by testing that `min_font_size` and `max_font_size` do not throw an error)
1. Test changes
1. Push a pull request (PR)
1. We will review the PR and when everything is okay, we will merge it!

Look forward to see your PR! 
regards
