### ISSUE TITLE
Add replace_punctuation and replace_digits

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#8]
Example:

```
>>> replace_digits(pd.Series("123"), "#", block=True)
pd.Series(["#"])
```

```
>>> replace_digits(pd.Series("123"), "#", block=False)
pd.Series(["###"])
```

(arguments name can be changed)

**Comment by ParthGandhi** [comment]
Why a new method and not overload the existing method?

In fact maybe you don't need a `remove` at all? just a `replace` with a default `replace_with=""` is equivalent to a remove.

**Comment by jbesomi** [comment]
True. You want to implement it?

**Comment by selimelawwa** [comment]
@jbesomi I think this issue should be closed.
