### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './_build/html/preprocessing.html'

### ISSUE THREAD

**Issue by vidyap-xgboost** [jbesomi/texthero#81]
I'm trying to run unit tests on my Ubuntu 18.04

I keep getting this error when I run `./check.sh`:

```python
Format code.
All done! ✨ 🍰 ✨
6 files left unchanged.
All done! ✨ 🍰 ✨
6 files left unchanged.
Update documentation.
/bin/sh: 1: sphinx-build: not found
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 127
Traceback (most recent call last):
  File "./to_docusaurus.py", line 143, in <module>
    to_md(in_html_filename, out_md_filename, id, title, hide_title)
  File "./to_docusaurus.py", line 88, in to_md
    with open(in_html_filepath, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './_build/html/preprocessing.html'
```
This is the file its running: [to_docusaurus.py](https://github.com/jbesomi/texthero/blob/master/docs/to_docusaurus.py)

I did pull the latest code.
Is that particular file moved to somewhere else?

**Comment by jbesomi** [comment]
Hey!

The problem arises there: `/bin/sh: 1: sphinx-build: not found`. 

[sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) it's executed from the command line and is used to create the documentation. In theory (correct me if I'm wrong), this should be installed automatically when sphinx is installed with pip (`pip install -U sphinx`).

For solving your issue:

1. Check from the command line that `sphinx-build` execute (i.e is correctly installed)
1. If not, try to update sphinx and try again (`pip install -U sphinx`)
1. If it does still not work, it probably means your $path is not correctly update and `sphinx-build` is not present
1. Once fixed, `./check.sh` should work (hopefully)

Please let me know how it goes! For you to know, we will have to update CONTRIBUTING.md to make everything more clear. Also, look at #40, soon we will have to move from Docusaurus to Sphinx. If you are interested in collaborating with this very important task let me know! We can do it together if you wish 👍

**Comment by vidyap-xgboost** [comment]
Yes, it was a problem with my $path and once I fixed it, `./check.sh` !

Thank you!

**Comment by jbesomi** [comment]
Great you solved! :)
