### ISSUE TITLE
Parameters in the hero.clean() function to activate individual pre-processing steps

### ISSUE THREAD

**Issue by jbesomi** [jbesomi/texthero#9]
It would be cool to have parameters in the hero.clean() function to activate individual pre-processing steps instead of constructing a custom pipeline.

Proposal by @mxhofer

Notes: the solution should keep the `clean` function simple to read and use.

**Comment by selimelawwa** [comment]
@jbesomi Would you suggest to add a **kwargs parameter to the clean function? or add some parameters with default value?

**Comment by jbesomi** [comment]
Texthero's aim to be very simple. This enhancement would require to add many arguments to the clean function. Furthermore, in this case, the easiest solution would consist of just creating a custom pipeline: #38
